### ISSUE TITLE
Around half height title bar after clicking a toot from notifications

### ISSUE THREAD

**Issue by hughesjeff** [unascribed/sleeping.town#31] opened 2018-06-09 22:32 UTC
Reproduce:
Open up your Notifications
Click any toot

It doesn't do it EVERY time, but it does it most times. 

https://yato.io/Screenshots/82b00d.png

**Comment by unascribed** [comment] 2018-06-10 12:19
Duplicate of #22

**Closed by unascribed** 2018-06-10 12:19 UTC
