### ISSUE TITLE
Visual artifacts during page load

### ISSUE THREAD

**Issue by falkreon** [unascribed/sleeping.town#51] opened 2018-11-13 15:13 UTC
Very minor cosmetic glitch: While the page is loading, the jagged page-tear decoration at the bottom of the window appears briefly on all borders of the window instead.

Affected versions: Sleeping v2
Affected browsers: Firefox Quantum 61.0.1(64-bit), Waterfox

**Comment by unascribed** [comment] 2018-11-14 12:20
This is caused by Sleeping v2 being injected into the Glitch theme upon page load, rather than being an actual theme file managed by Mastodon and Webpacker.

Specifically, the zig zag is being injected before the rest of the Sleeping CSS loads. The Sleeping JS *could* wait for the CSS to load before executing to mitigate this, which will result in less obvious and annoying artifacting from showing the unmodified Glitch theme briefly.

**Comment by unascribed** [comment] 2018-11-15 09:47
Fixed in z188

**Closed by unascribed** 2018-11-15 09:47 UTC
Labels: f: Sleeping, n: Firefox, p: Minor
